/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/library/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get library statistics */
        get: operations["getLibraryStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List library tracks */
        get: operations["getLibraryTracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start embeddings processing */
        post: operations["processLibrary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/process/server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start server-side processing */
        post: operations["processLibraryOnServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/process/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop processing */
        post: operations["stopProcessing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get processing progress */
        get: operations["getProcessingProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search by text */
        get: operations["searchText"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search by audio file */
        post: operations["searchAudio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compute/search/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute text search on server */
        post: operations["computeTextSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compute/search/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute audio search on server */
        post: operations["computeAudioSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/similar/by_track/{track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Similar tracks by track_id */
        get: operations["getSimilarByTrack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get configuration */
        get: operations["getConfig"];
        put?: never;
        /** Save configuration */
        post: operations["saveConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/task/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get task status */
        get: operations["getTaskStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TrackResponse: {
            artist: string;
            album: string;
            title: string;
            filepath: string;
            media_server_rating_key: string;
            media_server_type: string;
        };
        SearchResultResponse: {
            track: components["schemas"]["TrackResponse"];
            similarity_score: number;
            distance: number;
        };
        TrackDatabaseStats: {
            total_tracks: number;
            processed_tracks: number;
            unprocessed_tracks: number;
            progress_percentage: number;
            is_processing?: boolean | null;
            latest_session?: {
                [key: string]: unknown;
            } | null;
        };
        LibraryStatsResponse: {
            total_embeddings: number;
            collection_name: string;
            database_path: string;
            track_database_stats?: components["schemas"]["TrackDatabaseStats"];
        };
        TracksListResponse: {
            tracks: components["schemas"]["TrackResponse"][];
            total_count: number;
            page: number;
            limit: number;
        };
        ProcessingResponse: {
            /** @enum {string} */
            status: "processing" | "confirmation_required" | "already_running" | "worker_processing_started" | "worker_error" | "no_workers" | "server_started";
            message?: string | null;
            task_id?: string | null;
            track_id?: string | null;
            query?: string | null;
            filename?: string | null;
            active_workers?: number | null;
            tasks_created?: number | null;
            confirmation_required?: boolean | null;
        };
        SaveConfigResponse: {
            message: string;
            status: string;
            reloaded: boolean;
            reload_error?: string | null;
        };
        MediaServerSection: {
            type: string;
        };
        PlexSection: {
            url: string;
            token?: string | null;
            music_library_name: string;
        };
        ServerSection: {
            gpu_batch_size: number;
        };
        APISection: {
            host: string;
            port: number;
            reload: boolean;
        };
        ChromaSection: {
            collection_name: string;
            batch_size: number;
        };
        ClapSection: {
            model_id: string;
            target_sr: number;
            chunk_duration_s: number;
            num_chunks: number;
            max_load_duration_s?: number | null;
        };
        LoggingSection: {
            level: string;
        };
        ConfigResponse: {
            media_server: components["schemas"]["MediaServerSection"];
            plex: components["schemas"]["PlexSection"];
            server: components["schemas"]["ServerSection"];
            api: components["schemas"]["APISection"];
            chroma: components["schemas"]["ChromaSection"];
            clap: components["schemas"]["ClapSection"];
            logging: components["schemas"]["LoggingSection"];
        };
        ScanLibraryResponse: {
            message: string;
            total_tracks: number;
            new_tracks: number;
            updated_tracks: number;
            scan_timestamp: string;
        };
        StopProcessingResponse: {
            message: string;
            type?: string | null;
            cleared_tasks?: number | null;
        };
        TaskStatusResponse: {
            task_id: string;
            status: string;
            track_id?: string | null;
            started_at?: string | null;
            completed_at?: string | null;
            error_message?: string | null;
            search_results?: components["schemas"]["SearchResultResponse"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLibraryStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryStatsResponse"];
                };
            };
        };
    };
    getLibraryTracks: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                artist?: string;
                album?: string;
                title?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracksListResponse"];
                };
            };
        };
    };
    processLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingResponse"];
                };
            };
        };
    };
    processLibraryOnServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingResponse"];
                };
            };
        };
    };
    stopProcessing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopProcessingResponse"];
                };
            };
        };
    };
    getProcessingProgress: {
        parameters: {
            query?: {
                model_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackDatabaseStats"];
                };
            };
        };
    };
    searchText: {
        parameters: {
            query: {
                q: string;
                n_results?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Processing/confirmation response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingResponse"];
                };
            };
        };
    };
    searchAudio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    audio?: string;
                    /** @default 10 */
                    n_results?: number;
                };
            };
        };
        responses: {
            /** @description Processing/confirmation response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingResponse"];
                };
            };
        };
    };
    computeTextSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    query: string;
                    /** @default 10 */
                    n_results?: number;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultResponse"][];
                };
            };
        };
    };
    computeAudioSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    audio?: string;
                    /** @default 10 */
                    n_results?: number;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultResponse"][];
                };
            };
        };
    };
    getSimilarByTrack: {
        parameters: {
            query?: {
                n_results?: number;
            };
            header?: never;
            path: {
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultResponse"][] | components["schemas"]["ProcessingResponse"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    saveConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigResponse"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveConfigResponse"];
                };
            };
        };
    };
    getTaskStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
        };
    };
}
